---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(XML)
library(rvest)
library(tidyverse)
library(stringr)
library(sf)
```


# Geocoding 
## Get data with region's names
```{r}
regions_data <- readRDS("../data/raw/gadm36_UKR_1_sf.rds")
regions_data$NAME_1
```
Add ukrainians names of regions:
```{r}
regions_data$NL_NAME_1 <- c("Черкаська", "Чернігівська", " Чернівецька",
                            "АР Крим", "Дніпропетровська", "Донецька",
                            "Івано-Франківська", "Харківська", "Херсонська",
                            "Хмельницька", "Київська", "Київ", "Кіровоградська",
                            "Львівська", "Луганська", "Миколаївська", "Одеська", "Полтавська",
                            "Рівненська", "Севастопіль", "Сумська", "Тернопільська",
                            "Закарпатська", "Вінницька", "Волинська", "Запорізька",
                            "Житомирська")
```
## Transform column with coordinates
What is raw coordinate item?
```{r}
raw_data$coordinates[1]
```
How to get longitude (x)
```{r}
(x <- str_extract(raw_data$coordinates[1], "(\\d\\d.\\d+)"))
```
How to get latitude (y) 
```{r}
(y <- str_extract(raw_data$coordinates[1], "(?<=,)(\\d\\d.\\d+)"))
```
Test data 
```{r}
raw_data[1:10,] %>% 
  rename(old_coordinates = coordinates) %>% 
  mutate(longitude = str_extract(old_coordinates, "(\\d\\d.\\d+)") %>% 
           formatC(digits = 6, format = "f") %>% 
           as.numeric(),
         latitude = str_extract(old_coordinates, "(?<=,)(\\d\\d.\\d+)") %>%
           formatC(digits = 6, format = "f") %>% 
           as.numeric(),
         coordinates = map2(longitude, latitude, ~st_point(c(.x, .y))) %>% 
           st_sfc(crs = 4326), #-> test_df2
         region = map_chr(test_df2$coordinates, .f = function(x) {
           regions_data[which(st_intersects(regions_data$geometry, x, sparse = F)), ]$NL_NAME_1}))
  #select(-old_coordinates)
```
Another var:
```{r}
raw_data[1:10,] %>% 
  rename(old_coordinates = coordinates) %>% 
  mutate(coordinates = map(old_coordinates, function(x) {
    lon <- str_extract(x, "(\\d\\d.\\d+)") %>% 
      formatC(digits = 6, format = "f") %>% 
      as.numeric()
    
    lat <- str_extract(x, "(?<=,)(\\d\\d.\\d+)") %>%
      formatC(digits = 6, format = "f") %>% 
      as.numeric()
    
    return(map2(lon, lat, ~st_point(c(.x, .y))) %>%
           st_sfc(crs = 4326))
    }),
    
    region = map_chr(coordinates, .f = function(x) {
      regions_data[which(st_intersects(regions_data$geometry, x, sparse = F)), ]$NL_NAME_1})) %>% View()
```

```{r}
map1 <- readRDS("../../UKRmaps/sf/gadm36_UKR_0_sf.rds")
map2 <- readRDS("../../UKRmaps/sf/gadm36_UKR_1_sf.rds")
map3 <- readRDS("../../UKRmaps/sf/gadm36_UKR_2_sf.rds")
```
Make sf object from pairs of points:
```{r}
# Coordinates of Oster
st_point(c(x = 30.845993, y = 50.948692)) %>% 
  st_sfc(crs = 4326) -> oster_point

# Coordinates of Dymer
st_point(c(x = 30.261776, y = 50.779077)) %>% 
  st_sfc(crs = 4326) -> dymer_point
```

```{r}
(r1 <- st_intersects(map2[1:5,]$geometry, oster_point, sparse = F))
```
```{r}
map2[which(r1), ]$NAME_1
```

```{r}
(r2 <- st_contains(map2[2,]$geometry, dymer_point))
```

```{r}
map2$geometry[2][[1]][[1]][[1]][1:10, ]
```

