---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read xml-file:
```{r}
library(XML)
library(tidyverse)

short_data <- xmlParse("./data/test/short_base_data2.xml")
raw_data <- xmlParse("./data/raw/base_data.xml")
#bond <- xmlParse("./data/test/bond.xml")
```

### Test collect_nodes function
```{r}
map_dfr(company_type, function(x) {
  sprintf("//child::Folder[@id='%s']%s", x, nodes) %>% 
    node2dataframe(folder_data, col_names, nodes = ., company_type = x)
 }) %>% View()
```
Show snippet of code that enclosed within particular <Folder></Folder> node
```{r}
folder_data <- xmlParse("./data/test/base_data2.xml")
company_type <- xpathSApply(folder_data, "//Folder", xmlGetAttr, "id")

#getNodeSet(folder_data, "//Folder[@id='Industrial_parks']", fun = xmlValue)
#buf <- getNodeSet(folder_data, sprintf("//Folder[@id='%s']", company_type[2]))
```
Get whole data from node <Folder id="Industrial_parks">:
```{r}
"//Folder/name[contains(text(),'Industrial_parks')]"
#getNodeSet(base_data3, "//Folder/name[contains(text(),'Заводи, які будуються')]", fun = xmlValue)
(node <- getNodeSet(folder_data, "//child::Folder[@id='Industrial_parks']"))
```
Get node:
```{r}
getNodeSet(folder_data, sprintf("//child::Folder[@id='%s']%s", 'Industrial_parks', nodes[1]))
```

```{r}
getNodeSet(folder_data, sprintf("//child::Folder[@id='%s']%s", 'Industrial_parks', nodes[1])) %>% 
  xmlToDataFrame(nodes = ., collectNames = F, homogeneous = T, stringsAsFactors = F)
```

```{r}
#sprintf("//Folder/name[contains(text(),'%s')]%s", 'Діючі заводи', nodes) 
sprintf("//child::Folder[@id='%s']%s", 'Industrial_parks', nodes)
```

```{r}
nn <- sprintf("//child::Folder[@id='%s']%s", 'Industrial_parks', nodes)
node2dataframe(folder_data, col_names, nn)
```
Calculate number of companies of each type
```{r}
getNodeSet(folder_data, sprintf("//Folder[@id='%s']//name[last()]", company_type[2])) %>% length()
```


### TEST ZONE
Explore file structure:
```{r}
root <- xmlRoot(raw_data)
# Root's element name:
xmlName(root)
# Number of root's children:
xmlSize(root)
```

```{r}
getNodeSet(short_data, "//Placemark/name | //Point/coordinates")
df <- xmlToDataFrame(nodes = getNodeSet(short_data, "//Placemark/name | //Point/coordinates"),
                     collectNames = FALSE,
                     homogeneous = T)
```

```{r}
a1 <- read_xml("./data/raw/short_base_data2.xml")
```

Show all types of business:
```{r}
getNodeSet(raw_data, "//Folder/name", fun = xmlValue)
```
```{r}
getNodeSet(raw_data, "//Folder/name")
```
