---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(XML)
library(rvest)
library(tidyverse)
library(stringr)
library(sf)
```
Get data from tibble:
```{r}
raw_data <- readRDS("../data/processing/raw_data.rds")
```

# 1.Geocoding

## Get data with region's names
```{r}
regions_data <- readRDS("../data/raw/gadm36_UKR_1_sf.rds")
```
Add ukrainians names of regions:
```{r}
regions_data$NL_NAME_1 <- c("Черкаська", "Чернігівська", " Чернівецька",
                            "АР Крим", "Дніпропетровська", "Донецька",
                            "Івано-Франківська", "Харківська", "Херсонська",
                            "Хмельницька", "Київська", "Київ", "Кіровоградська",
                            "Львівська", "Луганська", "Миколаївська", "Одеська", "Полтавська",
                            "Рівненська", "Севастопіль", "Сумська", "Тернопільська",
                            "Закарпатська", "Вінницька", "Волинська", "Запорізька",
                            "Житомирська")
```

## Get regions according to places that contained in that regions
```{r}
geocoding_data <- raw_data %>% 
  rename(old_coordinates = coordinates) %>% 
  mutate(coordinates = map(old_coordinates, function(x) {
    
    # get coordinates from string "\n  24.2609999,49.911092,0\n "
    lon <- str_extract(x, "(\\d\\d.\\d+)") %>%
      formatC(digits = 6, format = "f") %>% 
      as.numeric()
    lat <- str_extract(x, "(?<=,)(\\d\\d.\\d+)") %>%
      formatC(digits = 6, format = "f") %>% 
      as.numeric()
    
    # transform pair coordinates to point object
    return(map2(lon, lat, ~st_point(c(.x, .y))) %>%
           st_sfc(crs = 4326))
    }),
    
    # find regions that contains corresponding points
    region = map_chr(coordinates, .f = function(x) {
      regions_data[which(st_intersects(regions_data$geometry, x, sparse = F)), ]$NL_NAME_1})) %>% 
  select(-old_coordinates, coordinates)
```

# 2. Extract working places

```{r}
geocoding_data %>% 
  mutate(working_place = str_extract(raw_data$description,
                                     "Кількість робочих місць:(\\s\\d+)") %>%
           str_extract('\\d+$') %>% as.numeric()) -> work_data
```

# 3. Extract info about amount of investments:

```{r}
work_data %>% 
  mutate(`investments, milliom UAH` = map_chr(.$description, function(x) {
        invest <- str_extract(x, "(\\s\\d+\\s[а-я]+(.|\\s|.\\s)(грн|€|\\$))")
        # Get amount
        amount <- str_extract(invest, "\\d+") %>% as.numeric()
        # Get volume
        volume <- str_extract(invest, "(млн|тис)")
        # Correct amount depending on volume
        amount <- ifelse(volume == "тис", amount * 0.001, amount) %>% as.numeric()
        # Get currency
        currency <- str_extract(invest, "(грн|€|\\$)")
        # Coerce amount to UAH  
        amount <- ifelse(!is.na(currency), switch(currency,
                                                  "$" = amount * 28,
                                                  "€" = amount * 32,
                                                  "грн" = amount),
                         NA)
  }
  ) %>% as.numeric()) -> investment_data
```

# 4. Make final tibble with replacing \r\n symbols from "name" column:

```{r}
final_tibble <- investment_data %>% 
  select(-description, - coordinates) %>% 
  mutate_at(vars(name), funs(gsub("[\r\n]", "", .)))

saveRDS(final_tibble, file = "../data/processing/final_data.rds")
```

Make tibble with Ukrainian titles:

```{r}
final_tibble %>% 
  rename(`Тип підприємства` = company_type, Підприємство = name,
         Область = region, `Кіл-ть робочих місць` = working_place,
         `Сума інвестицій, млн.грн` = `investments, milliom UAH`) %>% 
  mutate(`Тип підприємства` = map_chr(.$`Тип підприємства`, switch,
    "Industrial_parks" = "Індустріальні парки",
    "Working_Factories" = "Діючи заводи",
    "Future_Factories" = "Заводи, які будуються",
    "Power_Stations" = "Електростанції",
    "Elevators_Terminals" = "Елеватори/термінали",
    "Gas_Fields" = "Газові родовищ",
    "Others" = "Інші",
    "Livestock_Rooms" = "Тваринницькі приміщення")
    ) %>% 
  saveRDS(file = "../data/processing/final_ukr_data.rds")
```

# 5. Write csv-file:

```{r}
readRDS("../data/processing/final_data.rds") %>% 
  write_delim("../data/processing/final_data.csv", delim = ";")
```

With Ukrainian titles:
```{r}
readRDS("../data/processing/final_ukr_data.rds") %>% 
  write_delim("../data/processing/final_ukr_data.csv", delim = ";")
```

